import { useState } from 'react';
import { Download, FileText, ChevronDown, ChevronUp } from 'lucide-react';
import SectionHeader from '@/components/ui/SectionHeader';
import { useScrollReveal } from '@/hooks/useScrollReveal';

interface SourceGroup {
  title: string;
  sources: string[];
}

const sourceGroups: SourceGroup[] = [
  {
    title: 'Community Resources & Organizations',
    sources: [
      'Tracy Interfaith Ministries. (2026). Emergency food and clothing services. https://tracyinterfaith.org',
      'Tracy Community Connections Center. (2026). Homelessness services in Tracy, CA. https://tracyccc.org',
      'City of Tracy. (2026). Parks, recreation, and community services. https://www.cityoftracy.org',
      'Lolly Hansen Senior Center. (2026). Senior programs and resources. https://www.cityoftracy.org/our-city/departments/parks-recreation-department/seniors',
      'San Joaquin County Human Services Agency. (2026). Community support services. https://www.sjgov.org/hsa',
    ],
  },
  {
    title: 'Mental Health Resources',
    sources: [
      'A To Z Psychotherapy. (2025). Mental health services for women and children. https://www.atozpsychotherapy.org',
      'Mindpath Health. (2026). Psychiatrists and therapists in Tracy, CA. https://www.mindpath.com/provider/psychiatrist/ca/tracy',
      'Psychology Today. (2026). Verified therapists in Tracy, CA. https://www.psychologytoday.com/us/therapists/ca/tracy',
      "Razan's Therapy Services. (2026). Individual and couples counseling in Tracy, CA. https://razanstherapeuticservices.com",
      '988 Suicide & Crisis Lifeline. (2026). https://988lifeline.org',
      'Crisis Text Line. (2026). https://www.crisistextline.org',
    ],
  },
  {
    title: 'Events & Activities',
    sources: [
      'City of Tracy. (2026). City calendar and events. https://www.cityoftracy.org/I-Want-To/View/City-Calendar',
      'Tracy Earth Project. (2026). Annual Earth Day event. https://tracyearthproject.org',
      'Tracy Connects. (2026). Community resource fair. https://www.tracyconnects.com',
      'Eventbrite. (2026). Tracy, CA events and calendar. https://www.eventbrite.com/d/ca--tracy/events',
      'Tracy Community Band. (2026). Concert schedule. https://atthegrand.org/events/tracy-community-band',
    ],
  },
  {
    title: 'Volunteer & Nonprofit Organizations',
    sources: [
      'Animal Rescue of Tracy. (2026). Volunteer programs. https://www.animalrescuetracy.org/volunteering',
      'Tracy Interfaith Ministries. (2026). Volunteer opportunities. https://tracyinterfaith.org',
      'Tracy Grand Theater Center for the Arts. (2026). Volunteer program. https://atthegrand.org',
      'GreatNonprofits. (2026). Nonprofits and charities in Tracy, CA. https://greatnonprofits.org/city/tracy/CA',
      'Tracy Community Connections Center. (2026). Volunteer and donation information. https://tracyccc.org/get-involved',
      'Tracy Earth Project. (2026). Volunteer opportunities. https://tracyearthproject.org',
    ],
  },
  {
    title: 'Youth & Education Programs',
    sources: [
      'Boys & Girls Club of Tracy. (2026). After-school programs and tutoring. https://www.bgca.org',
      'Give Every Child a Chance. (2026). Free tutoring services. https://www.gecac.net',
      'Tracy Unified School District. (2026). Community education programs.',
    ],
  },
  {
    title: 'Images & Media',
    sources: [
      'All photographs and illustrations were generated by the team using AI image generation tools.',
      'Icons sourced from Lucide React (open-source, MIT license). https://lucide.dev',
    ],
  },
];

function AccordionItem({ title, children, defaultOpen = true }: { title: string; children: React.ReactNode; defaultOpen?: boolean }) {
  const [isOpen, setIsOpen] = useState(defaultOpen);

  return (
    <div className="border border-border rounded-lg overflow-hidden mb-4">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-center justify-between p-4 bg-white hover:bg-lightgray transition-colors text-left"
        aria-expanded={isOpen}
      >
        <h3 className="font-semibold text-navy">{title}</h3>
        {isOpen ? <ChevronUp className="w-5 h-5 text-textsecondary" /> : <ChevronDown className="w-5 h-5 text-textsecondary" />}
      </button>
      {isOpen && (
        <div className="p-4 bg-white border-t border-border">
          {children}
        </div>
      )}
    </div>
  );
}

export default function References() {
  const { ref: headerRef, isRevealed: headerRevealed } = useScrollReveal<HTMLDivElement>(0.05);

  return (
    <main id="main-content">
      {/* Page Header */}
      <section className="bg-navy py-20 pb-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div ref={headerRef} className={`reveal ${headerRevealed ? 'revealed' : ''}`}>
            <span className="inline-block text-xs font-medium uppercase tracking-widest text-sky mb-3">
              References & Attribution
            </span>
            <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">
              Sources & Documentation
            </h1>
            <p className="text-lg text-white/80 max-w-2xl">
              All external sources, citations, and required TSA competition documents.
            </p>
          </div>
        </div>
      </section>

      {/* Required Documents */}
      <section className="py-12 bg-lightgray">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-white rounded-lg border border-border p-6 text-center card-hover">
              <FileText className="w-10 h-10 text-navy mx-auto mb-4" />
              <h3 className="text-lg font-semibold text-navy mb-2">Student Copyright Checklist</h3>
              <p className="text-sm text-textsecondary mb-4">
                Required TSA document confirming all content permissions and original work.
              </p>
              <button
                onClick={() => alert('PDF download would open the Student Copyright Checklist document.')}
                className="inline-flex items-center gap-2 bg-navy text-white font-semibold px-5 py-2.5 rounded-lg hover:bg-navy-dark transition-colors"
              >
                <Download className="w-4 h-4" />
                Download PDF
              </button>
            </div>
            <div className="bg-white rounded-lg border border-border p-6 text-center card-hover">
              <FileText className="w-10 h-10 text-navy mx-auto mb-4" />
              <h3 className="text-lg font-semibold text-navy mb-2">Work Log</h3>
              <p className="text-sm text-textsecondary mb-4">
                Complete development timeline and team member contributions.
              </p>
              <button
                onClick={() => alert('PDF download would open the Work Log document.')}
                className="inline-flex items-center gap-2 bg-navy text-white font-semibold px-5 py-2.5 rounded-lg hover:bg-navy-dark transition-colors"
              >
                <Download className="w-4 h-4" />
                Download PDF
              </button>
            </div>
          </div>
          <p className="text-xs text-textsecondary text-center mt-6">
            <span className="font-semibold">Note:</span> These documents are required per TSA Webmaster competition rules. 
            Failure to include results in disqualification. In a production environment, these would link to actual PDF files.
          </p>
        </div>
      </section>

      {/* Sources by Category */}
      <section className="py-16 bg-offwhite">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <SectionHeader eyebrow="Sources" title="References by Category" align="left" />
          <div className="mt-10">
            {sourceGroups.map((group) => (
              <AccordionItem key={group.title} title={group.title}>
                <ul className="space-y-3">
                  {group.sources.map((source, i) => (
                    <li key={i} className="text-sm text-textsecondary pl-4 border-l-2 border-sky/30">
                      {source}
                    </li>
                  ))}
                </ul>
              </AccordionItem>
            ))}
          </div>
        </div>
      </section>

      {/* Framework Statement */}
      <section className="py-12 bg-navy-light">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h3 className="text-lg font-semibold text-navy mb-4">Custom-Built Framework Statement</h3>
          <p className="text-navy/80 leading-relaxed">
            This website was built entirely from scratch by the TSA Webmaster team. No pre-built templates, 
            themes, or frameworks (such as WordPress, Bootstrap themes, or purchased templates) were used. 
            All HTML, CSS, and JavaScript were written by team members during the current school year. 
            The site uses React for component organization and Tailwind CSS for styling utilities, 
            both configured from their bare npm packages without any pre-made theme or template files.
          </p>
        </div>
      </section>
    </main>
  );
}
